---

- name: Convert an ubuntu machine into a docker host
  hosts: all
  become: yes
  roles:
    - role: angstwad.docker_ubuntu
      kernel_pkg_state: present
      docker_group_members: [ "{{ username }}" ]
